FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-utils wget software-properties-common gnupg

RUN env DEBIAN_FRONTEND=noninteractive \
        apt-get update; \
        apt-get install -y --no-install-recommends \
            python3 python3-pip \
            gcc g++ build-essential cmake make git graphviz flex bison libc6; \
    git clone https://github.com/doxygen/doxygen.git /tmp/doxygen; \
        cd /tmp/doxygen; \
        git checkout 9b262a41ec2b1bcc2b64f7364730d164eeb3f2f5; \
        mkdir build; \
        cd build; \
        cmake .. -DCMAKE_BUILD_TYPE=Release; \
        make -j8; \
        make install; \
        rm -rf /tmp/doxygen \
    apt-get remove gcc g++ build-essential

RUN pip3 install sphinx==4.5.0 breathe sphinx-rtd-theme recommonmark myst_parser

RUN ldconfig
