set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)


set(TOOLCHAIN_PREFIX arm-none-eabi-)

find_program(ARM_GCC_EXECUTABLE NAMES ${TOOLCHAIN_PREFIX}gcc REQUIRED)
get_filename_component(ARM_TOOLCHAIN_DIR "${ARM_GCC_EXECUTABLE}" DIRECTORY)

set(CMAKE_C_COMPILER "${ARM_GCC_EXECUTABLE}")
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER "${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}g++")

set(CMAKE_OBJCOPY ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")

set(CMAKE_SYSROOT ${ARM_TOOLCHAIN_DIR}/../arm-none-eabi)
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# set(MCU_FPU fpv4-sp-d16)

# set(COMMON_FLAGS "-mcpu=${MCU_ARCH} -mthumb -mfloat-abi=${MCU_FLOAT_ABI} -ffunction-sections -fdata-sections -g -fno-common -fmessage-length=0 --specs=nosys.specs")

# if (MCU_FLOAT_ABI STREQUAL hard)
#     set(COMMON_FLAGS "${COMMON_FLAGS} -mfpu=${MCU_FPU}")
# endif ()

# set(CMAKE_CXX_FLAGS "${COMMON_FLAGS} ")
# set(CMAKE_C_FLAGS "${COMMON_FLAGS} -std=gnu99")

# set(STDLIBS "-lc -lm -lnosys")
# set(CMAKE_EXE_LINKER_FLAGS "-Wl,--gc-sections ${STDLIBS} -T ${MCU_LINKER_SCRIPT}")
# set(LINKER_LANGUAGE CXX)

if(CMAKE_BUILD_TYPE MATCHES Debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -gdwarf-2")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g -gdwarf-2")
endif()
