[package]
name = "rofi_voxel"
version = "0.1.0"
edition = "2021"

[profile.rel-with-deb-info]
inherits = "release"
debug = true
[profile.min-size-rel]
inherits = "release"
opt-level = "s"

[lib]
name = "rofi_voxel_cli"
crate-type = [ "lib", "cdylib", "staticlib" ]

[dependencies]
rofi_voxel_reconfig = { path = "../../softwareComponents/voxelReconfig" }

amplify = "3.14"
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
clap-verbosity-flag = "2.0"
itertools = "0.10"
log = "0.4"
log4rs = "1.2"
num = "0.4"
serde_json = "1.0"
