[package]
name = "rofi_voxel"
version = "0.1.0"
edition = "2021"

[lib]
name = "rofi_voxel_cli"
crate-type = [ "lib", "cdylib", "staticlib" ]


[dependencies]
rofi_voxel_reconfig = { path = "../../softwareComponents/voxelReconfig" }

anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
clap-verbosity-flag = "2.0"
log = "0.4"
serde_json = "1.0"
simplelog = "0.12"
itertools = "0.10"
