[package]
name = "rofi_voxel_reconfig"
version = "0.1.0"
edition = "2021"

[lib]
name = "rofi_voxel_cli"
crate-type = [ "lib", "cdylib", "staticlib" ]


[[bin]]
name = "rofi-voxel_reconfig"

[dependencies]
rofi_voxel = { path = "../../softwareComponents/rust-rofi_voxel" }

anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
clap-verbosity-flag = "2.0"
log = "0.4"
serde_json = "1.0"
simple-logging = "2.0"
itertools = "0.10"
