[package]
name = "rofi_voxel_reconfig"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rofi-voxel_reconfig"

[dependencies]
rofi_voxel = { path = "../../softwareComponents/rust-rofi_voxel" }

anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
serde_json = "1.0"
itertools = "0.10"
