#!/usr/bin/env bash

if [[ $# -ne 2 ]] ; then
    >&2 echo "Expected 2 args: <input_world_file> <goal_world_file>"
    exit 1
fi

if [ -z "$ROFI_BUILD_DIR" ]; then
    >&2 echo "ROFI_BUILD_DIR is not set. Are you in RoFI environment?";
    exit 1;
fi

TMP_DIR="$ROFI_BUILD_DIR/desktop/tmp"
mkdir -p "$TMP_DIR" || exit 1

INIT_ROFI_WORLD_FILE=$(mktemp "$TMP_DIR/tmp.init_rofi_world.XXXXXX.json")
GOAL_ROFI_WORLD_FILE=$(mktemp "$TMP_DIR/tmp-goal_rofi_world.XXXXXX.json")
trap "rm -f \"$INIT_ROFI_WORLD_FILE\" \"$INIT_ROFI_WORLD_FILE\"" EXIT INT QUIT TERM

rofi-convert --if=old "$1" "$INIT_ROFI_WORLD_FILE" \
    || { >&2 echo -e "\nError while converting init world from old cfg"; exit 1; }
rofi-convert --if=old "$2" "$GOAL_ROFI_WORLD_FILE" \
    || { >&2 echo -e "\nError while converting goal world from old cfg"; exit 1; }

rofi-voxel "$INIT_ROFI_WORLD_FILE" "$GOAL_ROFI_WORLD_FILE"

rm -f "$INIT_ROFI_WORLD_FILE" "$GOAL_ROFI_WORLD_FILE"
