[package]
name = "rofi_voxel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "lib", "cdylib" ]

[dependencies]
amplify = "3.13.0"
enum-iterator = "1.2.0"
modular-bitfield = "0.11.2"
num = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
static_assertions = "1.1.0"
