[package]
name = "rofi_voxel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "lib", "cdylib", "staticlib" ]

[features]
cpp_json_bindings = ["dep:serde_json", "dep:failure"]

[dependencies]
amplify = "3.13"
bimap = "0.6"
enum-iterator = "1.2"
itertools = "0.10"
modular-bitfield = "0.11"
num = "0.4"
rs-graph = "0.20"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.8"
static_assertions = "1.1"

serde_json = { version="1.0", optional = true }
failure = { version="0.1", optional = true }

[dev-dependencies]
serde_json = "1.0"
