[package]
name = "rofi_voxel"
version = "0.1.0"
authors = [ "Ondřej Svoboda <xsvobo25@fi.muni.cz>" ]
edition = "2021"
publish = false
repository = "https://github.com/paradise-fi/RoFI"

[lib]
crate-type = [ "lib", "cdylib", "staticlib" ]

[features]
default = [ "cpp_json_bindings" ]
cpp_json_bindings = [ "dep:serde_json", "dep:failure", "dep:cxx", "dep:cxx-build" ]

[dependencies]
amplify = "3.13.0"
bimap = "0.6.2"
enum-iterator = "1.2.0"
itertools = "0.10.5"
modular-bitfield = "0.11.2"
num = "0.4.0"
rs-graph = "0.20.1"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.8.1"
static_assertions = "1.1.0"

cxx = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
failure = { version = "0.1.8", optional = true }

[build-dependencies]
cxx-build = { version = "1.0", optional = true }
