[package]
name = "rofi_voxel_reconfig"
version = "0.2.0"
edition = "2021"

[profile.rel-with-deb-info]
inherits = "release"
debug = true
[profile.min-size-rel]
inherits = "release"
opt-level = "s"

[lib]
crate-type = [ "lib", "cdylib", "staticlib" ]

[dependencies]
amplify = "3.13"
bimap = "0.6"
enum-iterator = "1.2"
itertools = "0.10"
log = "0.4"
modular-bitfield = "0.11"
num = "0.4"
rs-graph = "0.20"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.8"
static_assertions = "1.1"
