[package]
name = "rofi_voxel_reconfig"
version = "0.2.0"
edition = "2021"

[profile.rel-with-deb-info]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true
[profile.min-size-rel]
inherits = "release"
opt-level = "s"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
amplify = "4.0"
bimap = "0.6"
educe = "0.4"
enum-iterator = "1.2"
iter_fixed = "0.3"
itertools = "0.11"
lapjv = "0.2"
litemap = "0.7"
log = "0.4"
modular-bitfield = "0.11"
ndarray = "0.13"                                   # In sync with crate lapjv
num = "0.4"
ordered-float = "4.1"
rs-graph = "0.21"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.10"
static_assertions = "1.1"

[dev-dependencies]
multicode = { path = "multicode" }
