name: "Build & test"
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
jobs:
  build_desktop:
    name: "Build suite desktop"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - environment: Debug
            image: ghcr.io/paradise-fi/rofi.debian
            cmake_flags: -DBUILD_HEADLESS=ON -DBUILD_GAZEBO=OFF
            run_tests: true
          - environment: Release
            image: ghcr.io/paradise-fi/rofi.debian
            cmake_flags: -DBUILD_HEADLESS=ON -DBUILD_GAZEBO=OFF
            run_tests: true
          - environment: Debug
            image: ghcr.io/paradise-fi/rofi.ubuntu
            cmake_flags: -DBUILD_GAZEBO=ON -DBUILD_GZ_SIMULATOR=ON
            run_tests: false
          - environment: Release
            image: ghcr.io/paradise-fi/rofi.ubuntu
            cmake_flags: -DBUILD_GAZEBO=ON -DBUILD_GZ_SIMULATOR=ON
            run_tests: false
    defaults:
      run:
        shell: bash
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          source setup.sh ${{ matrix.environment }}
          rcfg desktop -- ${{ matrix.cmake_flags }}
          rmake desktop
      - name: Run tests
        if: ${{ matrix.run_tests }}
        run: |
          source setup.sh ${{ matrix.environment }}
          rmake --test --all
  build_esp32:
    name: "Build suite esp32"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        environment: [Debug, Release]
    container:
      image: ghcr.io/paradise-fi/rofi.debian
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          source setup.sh -i ${{ matrix.environment }}

          # Provide secrets
          export ROFI_SSID="N/A"
          export ROFI_WIFI_PASS=""
          export ROFI_WLAN_USER=""
          export RoFI_WLAN_PASS=""

          # Configure and build
          rcfg esp32
          rmake esp32
  build_stm32:
    name: "Build suite stm32"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        environment: [Debug, Release]
    container:
      image: ghcr.io/paradise-fi/rofi.debian
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          source setup.sh ${{ matrix.environment }}

          # Configure and build
          rcfg stm32
          rmake stm32
  build_doc:
    name: "Build documentation"
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/paradise-fi/rofi.doc
    defaults:
      run:
        shell: bash
    steps:
      # Work-around for https://github.com/actions/runner-images/issues/6775
      - name: Change Owner of Container Working Directory
        run: chown root:root .
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          source setup.sh Debug
          rcfg doc
          rmake doc
      - name: Build other branches
        if: github.ref == 'refs/heads/master'
        run: |
          echo ::group::Setting up repository for building all branches
          source setup.sh Debug
          # Fetch all branches
          git fetch --all
          git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | \
            while IFS= read -r remote
              do git branch --track "${remote#origin/}" "$remote" || true
            done
          git pull --all
          echo ::endgroup::

          releng/doc/buildAllBranches.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: build.Debug/doc/web
          retention-days: 14
  deploy:
    name: "Deploy documentation"
    runs-on: ubuntu-24.04
    needs: build_doc
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout # Required for GH-pages deployment
        uses: actions/checkout@v4
      - name: "Download web"
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: documentation
      - run: ls documentation
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: documentation
          single-commit: true
